import type { Template } from "@core/types/Template";
import type { PresetTemplateHelpers } from "../shared/templateHelpers";

export const createFeaturePresetTemplate = (_helpers: PresetTemplateHelpers): Template => ({
  nodeChildrenMap: {
    39640: [],
    81116: [611990, 94673, 195969],
    94673: [],
    152324: [],
    181050: [],
    195969: [],
    216838: [],
    317816: [],
    479732: [711696, 752926, 998573],
    533899: [],
    611990: [],
    0: [979227, 216838, 963823],
    711696: [],
    752926: [],
    761784: [39640, 181050, 533899],
    762069: [859081, 152324, 317816],
    859081: [],
    963823: [81116, 762069, 761784, 479732],
    979227: [],
    998573: [],
  },
  nodeStyleMap: {
    39640: {
      default: {
        textTransform: "uppercase",
        fontWeight: "bold",
        color: "#424242",
        fontSize: "12px",
        height: "18px",
      },
      hover: {},
      active: {},
    },
    81116: {
      default: {
        borderRadius: "24px",
        backgroundColor: "#E2F8DF",
        paddingLeft: "16px",
        paddingRight: "16px",
        flexDirection: "column",
        justifyContent: "center",
        display: "flex",
        paddingTop: "48px",
        paddingBottom: "48px",
      },
      hover: {},
      active: {},
    },
    94673: {
      default: {
        fontWeight: "600",
        marginTop: "12px",
        width: "318px",
      },
      hover: {},
      active: {},
    },
    152324: {
      default: {
        fontWeight: "600",
        marginTop: "12px",
        width: "318px",
      },
      hover: {},
      active: {},
    },
    181050: {
      default: {
        fontWeight: "600",
        marginTop: "12px",
        width: "318px",
      },
      hover: {},
      active: {},
    },
    195969: {
      default: {
        width: "fit-content",
        paddingTop: "4px",
        paddingRight: "8px",
        paddingLeft: "8px",
        paddingBottom: "4px",
        backgroundColor: "#000000",
        color: "#ffffff",
        borderRadius: "4px",
        cursor: "pointer",
        fontSize: "10px",
        marginTop: "32px",
        height: "21px",
      },
      hover: {},
      active: {},
    },
    216838: {
      default: {
        width: "90%",
        maxWidth: "600px",
        marginLeft: "auto",
        marginRight: "auto",
        marginTop: "24px",
        fontSize: "12px",
        textAlign: "center",
      },
      hover: {},
      active: {},
    },
    317816: {
      default: {
        width: "fit-content",
        paddingTop: "4px",
        paddingRight: "8px",
        paddingLeft: "8px",
        paddingBottom: "4px",
        backgroundColor: "#000000",
        color: "#ffffff",
        borderRadius: "4px",
        cursor: "pointer",
        fontSize: "10px",
        marginTop: "32px",
        height: "21px",
      },
      hover: {},
      active: {},
    },
    479732: {
      default: {
        borderRadius: "24px",
        backgroundColor: "#DFF5F7",
        paddingLeft: "16px",
        paddingRight: "16px",
        flexDirection: "column",
        justifyContent: "center",
        display: "flex",
        flexWrap: "nowrap",
        paddingTop: "48px",
        paddingBottom: "48px",
        marginTop: "24px",
      },
      hover: {},
      active: {},
    },
    533899: {
      default: {
        width: "fit-content",
        paddingTop: "4px",
        paddingRight: "8px",
        paddingLeft: "8px",
        paddingBottom: "4px",
        backgroundColor: "#000000",
        color: "#ffffff",
        borderRadius: "4px",
        cursor: "pointer",
        fontSize: "10px",
        marginTop: "32px",
        height: "21px",
      },
      hover: {},
      active: {},
    },
    611990: {
      default: {
        textTransform: "uppercase",
        fontWeight: "bold",
        color: "#424242",
        fontSize: "12px",
      },
      hover: {},
      active: {},
    },
    0: {
      default: {
        paddingTop: "48px",
        paddingBottom: "48px",
      },
      hover: {},
      active: {},
    },
    711696: {
      default: {
        textTransform: "uppercase",
        fontWeight: "bold",
        color: "#424242",
        fontSize: "12px",
      },
      hover: {},
      active: {},
    },
    752926: {
      default: {
        fontWeight: "600",
        marginTop: "12px",
        width: "318px",
      },
      hover: {},
      active: {},
    },
    761784: {
      default: {
        borderRadius: "24px",
        backgroundColor: "#F2E9F8",
        paddingLeft: "16px",
        paddingRight: "16px",
        flexDirection: "column",
        justifyContent: "center",
        display: "flex",
        flexWrap: "nowrap",
        paddingTop: "48px",
        paddingBottom: "48px",
        marginTop: "24px",
      },
      hover: {},
      active: {},
    },
    762069: {
      default: {
        borderRadius: "24px",
        backgroundColor: "#FEF2C1",
        paddingLeft: "16px",
        paddingRight: "16px",
        flexDirection: "column",
        justifyContent: "center",
        display: "flex",
        paddingTop: "48px",
        paddingBottom: "48px",
      },
      hover: {},
      active: {},
    },
    859081: {
      default: {
        textTransform: "uppercase",
        fontWeight: "bold",
        color: "#424242",
        fontSize: "12px",
      },
      hover: {},
      active: {},
    },
    963823: {
      default: {
        display: "flex",
        paddingTop: "16px",
        paddingBottom: "16px",
        paddingRight: "16px",
        paddingLeft: "16px",
        flexWrap: "wrap",
        flexDirection: "row",
        justifyContent: "space-evenly",
        width: "100%",
        maxWidth: "800px",
        marginLeft: "auto",
        marginRight: "auto",
        marginTop: "24px",
      },
      hover: {},
      active: {},
    },
    979227: {
      default: {
        textAlign: "center",
        width: "90%",
        fontSize: "24px",
        maxWidth: "600px",
        marginLeft: "auto",
        marginRight: "auto",
        fontWeight: "bold",
        fontVariant: "small-caps",
      },
      hover: {},
      active: {},
    },
    998573: {
      default: {
        width: "fit-content",
        paddingTop: "4px",
        paddingRight: "8px",
        paddingLeft: "8px",
        paddingBottom: "4px",
        backgroundColor: "#000000",
        color: "#ffffff",
        borderRadius: "4px",
        cursor: "pointer",
        fontSize: "10px",
        marginTop: "32px",
        height: "21px",
      },
      hover: {},
      active: {},
    },
  },
  nodeRecordMap: {
    39640: {
      name: "core:text",
      type: "core:text",
      content: "Style as you want",
    },
    81116: {
      name: "core:container",
      type: "core:container",
      styleUi: { background: { mode: "Solid" } },
    },
    94673: {
      name: "core:paragraph",
      type: "core:paragraph",
      content: "Move stuff around by clicking and start dragging",
    },
    152324: {
      name: "core:paragraph",
      type: "core:paragraph",
      content: "Easy to edit pre-built layout and sections.",
    },
    181050: {
      name: "core:paragraph",
      type: "core:paragraph",
      content: "Play around with css styles, make section anyhow you want",
    },
    195969: {
      name: "core:button",
      type: "core:button",
      content: "Start creating today",
      styleUi: { background: { mode: "Solid" } },
    },
    216838: {
      name: "core:paragraph",
      type: "core:paragraph",
      content:
        "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
    },
    317816: {
      name: "core:button",
      type: "core:button",
      content: "What are you waiting for",
      styleUi: { background: { mode: "Solid" } },
    },
    479732: {
      name: "core:container",
      type: "core:container",
      styleUi: { background: { mode: "Solid" } },
    },
    533899: {
      name: "core:button",
      type: "core:button",
      content: "Checkout styles properties",
      styleUi: { background: { mode: "Solid" } },
    },
    611990: {
      name: "core:text",
      type: "core:text",
      content: "Drag n Drop",
    },
    0: {
      name: "Feature",
      type: "core:container",
    },
    711696: {
      name: "core:text",
      type: "core:text",
      content: "Drag n Drop",
    },
    752926: {
      name: "core:paragraph",
      type: "core:paragraph",
      content: "Move stuff around by clicking and start dragging",
    },
    761784: {
      name: "core:container",
      type: "core:container",
      styleUi: { background: { mode: "Solid" } },
    },
    762069: {
      name: "core:container",
      type: "core:container",
      styleUi: { background: { mode: "Solid" } },
    },
    859081: {
      name: "core:text",
      type: "core:text",
      content: "Layouts and Sections ",
    },
    963823: {
      name: "core:row",
      type: "core:row",
    },
    979227: {
      name: "core:text",
      type: "core:text",
      content:
        "Develop, build and visualize your dream website - only sky is the limit",
    },
    998573: {
      name: "core:button",
      type: "core:button",
      content: "Start creating today ",
      styleUi: { background: { mode: "Solid" } },
    },
  },
});
