-- Initial migration placeholder.
-- Keep every schema change in timestamped files under supabase/migrations.
-- Example:
-- create table if not exists public.example (
--   id uuid primary key default gen_random_uuid(),
--   created_at timestamptz not null default now()
-- );
